#!bin/php
<?php

require __DIR__.'/bootstrap/bootstrap.php';

use App\Command\AddComment;
use App\Command\AddNews;
use App\Command\DeleteNews;
use App\Command\ReadNews;
use App\Command\ShowNews;
use Symfony\Component\Console\Application;

$application = new Application();

$application->addCommands([
    new ShowNews(),
    new AddNews(),
    new ReadNews(),
    new AddComment(),
    new DeleteNews()
]);

$application->run();

